# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ios_kn_sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_kn_sample
 
  pod 'lib', :path => '../lib/'
end
